### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by zingaburga** [faye/websocket-extensions-node#1]
Hi,
I haven't done much investigation into this, but I thought I'd post it anyway.
Is it possible for the pipeline to be used before it is initialised?  I've noticed the following exception in my application:

	Exception on "GET /websocket" in filter "raw_websocket":
	TypeError: Cannot call method 'processIncomingMessage' of undefined
		at instance.processIncomingMessage (/nodeserver/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
		at instance._emitMessage (/nodeserver/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:435:22)
		at instance._emitFrame (/nodeserver/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:398:19)
		at instance.parse (/nodeserver/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
		at IO.write (/nodeserver/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
		at new WebSocket (/nodeserver/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket.js:23:19)
		at App.exports.app.raw_websocket (/nodeserver/node_modules/sockjs/lib/trans-websocket.js:43:12)
		at execute_request (/nodeserver/node_modules/sockjs/lib/webjs.js:22:38)
		at IncomingMessage.req.next_filter (/nodeserver/node_modules/sockjs/lib/webjs.js:105:18)
		at Listener.webjs_handler (/nodeserver/node_modules/sockjs/lib/webjs.js:107:13)

Thank you.

**Comment by jcoglan** [comment]
For that call to work, `activate()` or `generateResponse()` must have been called first, which should happen as part of the client or server handshake.

Did you find out how to reproduce this?

**Comment by zingaburga** [comment]
I don't know how to reproduce it unfortunately.  I've just noticed it happening every now and then on my application.

**Comment by jcoglan** [comment]
Have you tried running the `master` branch of `faye-websocket`, `websocket-driver`, `websocket-extensions`? I've been fixing some other exceptions and this might be fixed by that work.

**Comment by lpinca** [comment]
I've just received the same error while running Primus tests.
Here is a way to reproduce the issue: https://github.com/faye/faye-websocket-node/issues/38#issuecomment-75261387

**Comment by zingaburga** [comment]
Thanks for finding and fixing it! :)

**Comment by zingaburga** [comment]
After running the latest faye websocket combo, unfortunately, this issue still seems to occur (slightly different line numbers for hybi.js, but otherwise identical):

	Exception on "GET /websocket" in filter "raw_websocket":
	TypeError: Cannot call method 'processIncomingMessage' of undefined
		at instance.processIncomingMessage (/nodeserver/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
		at instance._emitMessage (/nodeserver/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
		at instance._emitFrame (/nodeserver/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
		at instance.parse (/nodeserver/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
		at IO.write (/nodeserver/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
		at new WebSocket (/nodeserver/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket.js:24:19)
		at App.exports.app.raw_websocket (/nodeserver/node_modules/sockjs/lib/trans-websocket.js:43:12)
		at execute_request (/nodeserver/node_modules/sockjs/lib/webjs.js:22:38)
		at IncomingMessage.req.next_filter (/nodeserver/node_modules/sockjs/lib/webjs.js:105:18)
		at Listener.webjs_handler (/nodeserver/node_modules/sockjs/lib/webjs.js:107:13)

**Comment by jcoglan** [comment]
This should be fixed in https://github.com/faye/faye-websocket-node/commit/29b94290e9e3a8b5093906171c8c5f51cd9f237c.

**Comment by zingaburga** [comment]
Thanks! :)
