### ISSUE TITLE
Exception: no method 'close' in object '_pipeline'

### ISSUE THREAD

**Issue by kuba-wyrostek** [faye/websocket-extensions-node#2]
This is the stack trace of an error that started after upgrading to 0.1.1:

    /opt/sway-sfgw/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:142
        this._pipeline.close(callback, context);
                       ^
    TypeError: Object [object Object] has no method 'close'
        at instance.close (/opt/sway-sfgw/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:142:20)
        at instance.close (/opt/sway-sfgw/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:182:24)
        at instance.close (/opt/sway-sfgw/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:97:18)
        at Xc.k.Yb (/opt/sway-sfgw/node_modules/firebase/lib/firebase-node.js:67:280)
        at Xc.k.close (/opt/sway-sfgw/node_modules/firebase/lib/firebase-node.js:67:489)
        at Ed (/opt/sway-sfgw/node_modules/firebase/lib/firebase-node.js:83:369)
        at vd.close (/opt/sway-sfgw/node_modules/firebase/lib/firebase-node.js:83:265)
        at Xc.Ee (/opt/sway-sfgw/node_modules/firebase/lib/firebase-node.js:79:121)
        at $c (/opt/sway-sfgw/node_modules/firebase/lib/firebase-node.js:66:464)
        at Y.onmessage (/opt/sway-sfgw/node_modules/firebase/lib/firebase-node.js:65:236)

**Comment by jcoglan** [comment]
`this._pipeline` will either be an instance of https://github.com/faye/websocket-extensions-node/blob/master/lib/pipeline/index.js, or `undefined`. How are you triggering this?

**Comment by kuba-wyrostek** [comment]
I do not invoke this directly - I just use Firebase client in my project.

**Comment by jcoglan** [comment]
What I'm saying is, I don't see how `_pipeline` can be an object and not have a `close()` method.

**Comment by jcoglan** [comment]
I'm going to need as small an example of what you're running that causes this bug, or you need to find out what `_pipeline` is in this instance.

**Comment by kuba-wyrostek** [comment]
This is what console shows when I `console.log('Pipeline:', this._pipeline)` just before the line that cause an excpetion:

    Pipeline: { _in: undefined, _out: undefined }

**Comment by jcoglan** [comment]
That looks like you're running the `Extensions` class from 0.1.1 and the `Pipeline` class from 0.1.0.

**Comment by kuba-wyrostek** [comment]
OK, I owe you an apology. The tester in our company used `scp` to update software on target machine (the machine lacks CPU power, thus no `npm` there) and simply left old `pipeline.js` file in `lib` folder. I guess this file was loaded instead of `pipline/index.js`. Sorry for bothering you.

**Comment by jcoglan** [comment]
Hey, no apology necessary, I figured it must have been something like that.
